GO
USE grupo3
GO

/************************************/
/*          PROCEDIMIENTOS          */
/************************************/
 
-- Tabla MARCAS
GO
CREATE PROCEDURE Crear_Marcas @DESCRIPCION_MARCA VARCHAR(255)
AS
BEGIN
  INSERT INTO MARCAS (MARCA)
  VALUES(@DESCRIPCION_MARCA);												
END;
GO

GO
CREATE PROCEDURE Eliminar_Marcas @ID INT
AS
BEGIN
  DELETE FROM MARCAS WHERE MARCA_ID = @ID;
END
GO

GO
CREATE PROCEDURE Modificar_Marcas
  @ID INT,
  @DESCRIPCION_MARCA VARCHAR(255)
AS
BEGIN
  UPDATE MARCAS SET MARCA = @DESCRIPCION_MARCA WHERE MARCA_ID = @ID
END;
GO

-- Tabla TIPOS
GO
CREATE PROCEDURE Crear_Tipos
  @DESCRIPCION_TIPO VARCHAR(255)
AS
BEGIN
  INSERT INTO TIPOS(MARCA)
  VALUES(@DESCRIPCION_MARCA);
END;
GO

GO
CREATE PROCEDURE Eliminar_Marcas
  @ID INT
AS
BEGIN
  DELETE FROM MARCAS WHERE MARCA_ID = @ID;
END
GO

GO
CREATE PROCEDURE Modificar_Marcas
  @ID INT,
  @DESCRIPCION_MARCA VARCHAR(255)
AS
BEGIN
  UPDATE MARCAS SET MARCA = @DESCRIPCION_MARCA WHERE MARCA_ID = @ID
END;
GO

-- Tabla DEPOSITOS
GO
CREATE PROCEDURE Crear_Depositos @DESCRIPCION_TIPODEP VARCHAR(255)
AS
BEGIN
  INSERT INTO DEPOSITOS (TIPO_DEPOSITO)
  VALUES(@DESCRIPCION_TIPODEP);
END;

-- Tabla PERSONAS
GO
CREATE PROCEDURE Crear_Personas @NOMBRE VARCHAR(255),@DIRECCION VARCHAR(255),@TELEFONO VARCHAR(255), @CORREO_ELECTRONICO VARCHAR(255)
AS
BEGIN
  INSERT INTO PERSONAS(NOMBRE,DIRECCION,TELEFONO, CORREO_ELECTRONICO)
  VALUES(@NOMBRE,@DIRECCION,@TELEFONO,@CORREO_ELECTRONICO);												
END;
GO

GO
CREATE PROCEDURE Eliminar_Personas @ID INT
AS
BEGIN
  DELETE FROM PERSONAS WHERE PERSONA_ID = @ID;
END
GO

GO
CREATE PROCEDURE Modificar_Personas
  @ID INT,
  @NOMBRE VARCHAR(255),
  @DIRECCION VARCHAR(255),
  @TELEFONO VARCHAR(255),
  @CORREO_ELECTRONICO VARCHAR(255)
AS
BEGIN
  UPDATE PERSONAS SET NOMBRE = @NOMBRE,DIRECCION = @DIRECCION,TELEFONO = @TELEFONO,CORREO_ELECTRONICO = @CORREO_ELECTRONICO WHERE PERSONA_ID = @ID
END;
GO