GO
USE grupo3
GO

/************************************/
/*          PROCEDIMIENTOS          */
/************************************/

-- Tabla MARCAS
GO
CREATE PROCEDURE Crear_Marcas
  @DESCRIPCION_TIPODEP VARCHAR(255)
AS
BEGIN
  INSERT INTO DEPOSITOS
    (TIPO_DEPOSITO)
  VALUES(@DESCRIPCION_TIPODEP);
END;

-- Tabla DEPOSITOS
GO
CREATE PROCEDURE Crear_Depositos @DESCRIPCION_TIPODEP VARCHAR(255)
AS
BEGIN
  INSERT INTO DEPOSITOS (TIPO_DEPOSITO)
  VALUES(@DESCRIPCION_TIPODEP);
END;