CREATE VIEW Vista_Servicios_Realizados
AS
  SELECT
    SR.SERVICIO_REALIZADO_ID,
    SR.CLIENTE_ID,
    P.NOMBRE AS NOMBRE_CLIENTE,
    SR.FECHA,
    SR.DESCRIPCION,
    SR.FACTURADO
  FROM
    SERVICIOS_REALIZADOS SR
    JOIN
    CLIENTES C ON SR.CLIENTE_ID = C.CLIENTE_ID
    JOIN
    PERSONAS P ON C.PERSONA_ID = P.PERSONA_ID;


