CREATE VIEW Vista_Stocks_Productos
AS
  SELECT
    S.STOCK_ID,
    D.TIPO_DEPOSITO,
    P.DESCRIPCION AS PRODUCTO_DESCRIPCION,
    S.CANTIDAD_PRODUCTO
  FROM
    STOCKS S
    JOIN
    DEPOSITOS D ON S.DEPOSITO_ID = D.DEPOSITO_ID
    JOIN
    PRODUCTOS P ON S.PRODUCTO_ID = P.PRODUCTO_ID;
